services:
    frontend:
        build: .
        ports:
            - "8080:8080"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - .:/app:delegated
            - /app/node_modules
        command: npm run dev
